name: ql
 
on:
  push:
    branches: [ gh-pages ]
 
jobs:
  job_id_1: 
    runs-on: ubuntu-latest
    steps:
      - name: download
        env:
          URL: https://www.youtube.com/watch?v=GED3MbFogXg
        run:  |
          git clone https://github.com/KingRan/KR.git
          ls         
      # - name: commit
      #   run: |
      #       git config --global user.email 3196@qq.com
      #       git config --global user.name ndt
      #       git add .
      #       git commit -m "update" -a               
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
    
   # - name: Release
    #  uses: softprops/action-gh-release@v1
   #   with:
    #    files: ./tmp/*
   #   env:
     #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
